# Generated by Django 5.2.7 on 2025-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributeoption',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Ảnh thumbnail cho danh mục', null=True, upload_to='categories/thumbnails/', verbose_name='Ảnh đại diện danh mục'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload ảnh cho tùy chọn này (nếu attribute.has_image = True)', null=True, upload_to='products/attributes/%Y/%m/', verbose_name='Ảnh'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload ảnh sản phẩm', null=True, upload_to='products/gallery/%Y/%m/', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã model'),
        ),
    ]
