# Generated by Django 5.2.7 on 2025-11-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi đánh giá', primary_key=True, serialize=False, verbose_name='Mã đánh giá')),
                ('rating', models.IntegerField(help_text='Xếp hạng của đánh giá (1-5)', verbose_name='Xếp hạng')),
                ('comment', models.TextField(blank=True, help_text='Bình luận chi tiết của đánh giá', null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ đánh giá được tạo', verbose_name='Ngày tạo')),
                ('order_item', models.ForeignKey(help_text='Mục đơn hàng liên kết với đánh giá này', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.orderitem', verbose_name='Mục đơn hàng')),
            ],
        ),
    ]
