# Generated by Django 5.2.7 on 2025-11-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0003_remove_productattributeoption_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervoucher',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vouchers', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Người bán sở hữu voucher (NULL nếu là platform voucher)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người bán'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='ordervoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vouchers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='products.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Người bán'),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sellers', to='discount.voucher', verbose_name='Voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='uservoucher',
            unique_together={('user', 'voucher')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchercategory',
            unique_together={('voucher', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherproduct',
            unique_together={('voucher', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherseller',
            unique_together={('voucher', 'seller')},
        ),
    ]
