# Generated by Django 5.1.6 on 2025-10-01 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tỉnh/thành')),
                ('name', models.CharField(help_text='Tên đầy đủ của tỉnh/thành phố', max_length=100, unique=True, verbose_name='Tên tỉnh/thành')),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã xã/phường')),
                ('name', models.CharField(help_text='Tên đầy đủ của xã/phường', max_length=100, verbose_name='Tên xã/phường')),
                ('province', models.ForeignKey(help_text='Tỉnh/thành phố chứa xã/phường này', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='address.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Xã/Phường',
                'verbose_name_plural': 'Xã/Phường',
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hamlet',
            fields=[
                ('hamlet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thôn/xóm')),
                ('name', models.CharField(help_text='Tên đầy đủ của thôn/xóm', max_length=100, verbose_name='Tên thôn/xóm')),
                ('ward', models.ForeignKey(help_text='Xã/phường chứa thôn/xóm này', on_delete=django.db.models.deletion.CASCADE, related_name='hamlets', to='address.ward', verbose_name='Xã/Phường')),
            ],
            options={
                'verbose_name': 'Thôn/Xóm',
                'verbose_name_plural': 'Thôn/Xóm',
                'ordering': ['ward__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã địa chỉ')),
                ('detail', models.CharField(help_text='Số nhà, ngõ, đường, v.v.', max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, help_text='Đánh dấu là địa chỉ mặc định của người dùng', verbose_name='Địa chỉ mặc định')),
                ('user', models.ForeignKey(help_text='Người dùng sở hữu địa chỉ này', on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('hamlet', models.ForeignKey(blank=True, help_text='Thôn/xóm của địa chỉ (có thể để trống)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='address.hamlet', verbose_name='Thôn/Xóm')),
                ('province', models.ForeignKey(help_text='Tỉnh/thành phố của địa chỉ', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='address.province', verbose_name='Tỉnh/Thành phố')),
                ('ward', models.ForeignKey(help_text='Xã/phường của địa chỉ', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='address.ward', verbose_name='Xã/Phường')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-is_default', 'address_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_ward_per_province'),
        ),
        migrations.AddConstraint(
            model_name='hamlet',
            constraint=models.UniqueConstraint(fields=('ward', 'name'), name='unique_hamlet_per_ward'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
