# Generated by Django 5.2.7 on 2025-11-19 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_default_address_per_user',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên người nhận'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AlterField(
            model_name='address',
            name='hamlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.hamlet', verbose_name='Thôn/Xóm'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Địa chỉ mặc định'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.province', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.ward', verbose_name='Xã/Phường'),
        ),
        migrations.AlterField(
            model_name='hamlet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên thôn/xóm'),
        ),
        migrations.AlterField(
            model_name='hamlet',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hamlets', to='address.ward', verbose_name='Xã/Phường'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên tỉnh/thành'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên xã/phường'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='address.province', verbose_name='Tỉnh/Thành phố'),
        ),
    ]
